### ISSUE TITLE
Research in QA models

### ISSUE THREAD

**Issue by dimaischenko** [RobotVeraDS/vera-dialog#4]
- [x] Check new datasets
- [x] Check manual questions and answers datasets
- [x] Check keyword + LSTM hybrid model (calculate accuracy and other metrics for comparison)
- [x] Create some report with best model and params

**Comment by dimaischenko** [comment]
+ Check Context + Sentence classifier model

**Comment by dimaischenko** [comment]
+ Change model to batch mode
+ Provide some model downgrade experiments (grid search with different number of parameters) to find optimal smallest values for hidden_size and embedding_size

**Comment by y-bo** [comment]
[metrics_qa.txt](https://github.com/RobotVeraDS/vera-dialog/files/2293907/metrics_qa.txt)
